ALTER TABLE characters 
ADD COLUMN IF NOT EXISTS origin VARCHAR(200),
ADD COLUMN IF NOT EXISTS first_appearance VARCHAR(200),
ADD COLUMN IF NOT EXISTS occupation VARCHAR(200),
ADD COLUMN IF NOT EXISTS affiliation VARCHAR(200),
ADD COLUMN IF NOT EXISTS family TEXT,
ADD COLUMN IF NOT EXISTS notable_episodes TEXT,
ADD COLUMN IF NOT EXISTS personality TEXT,
ADD COLUMN IF NOT EXISTS goals TEXT;