ALTER TABLE universes 
ADD COLUMN IF NOT EXISTS coordinates VARCHAR(100),
ADD COLUMN IF NOT EXISTS danger_level VARCHAR(50),
ADD COLUMN IF NOT EXISTS discovery_date VARCHAR(100),
ADD COLUMN IF NOT EXISTS population VARCHAR(200),
ADD COLUMN IF NOT EXISTS technology VARCHAR(200),
ADD COLUMN IF NOT EXISTS related_characters TEXT;